# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2026 G4OCCT Contributors
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/worker"
    schedule:
      interval: "weekly"
